language: php

php:
  - '7.4'

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpstan
  - ./vendor/bin/phpunit
  - ./vendor/bin/psalm

jobs:
  include:
    - stage: lint
        script: composer phpstan
    - #
        script: composer psalm
    - stage: test
        script: composer test