language: php

php:
  - '7.4'

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit 

jobs:
  include:
    - env: PHPSTAN=true
        script: composer phpstan
